/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_myjni_Loader */

#ifndef _Included_com_example_myjni_Loader
#define _Included_com_example_myjni_Loader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_myjni_Loader
 * Method:    test
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_myjni_Loader_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
